version: '3.4'

services:
  client-angular:
    image: algoritmofifo
    build: .
    command: ng serve --host 0.0.0.0
    volumes:
      - .:/app  
    ports:
      - 4200:4200
      - 49153:49153
      - 9876:9876
      - 49152:49152




